#!/bin/bash

#imprime 'primeiro argumento' na tela
#Aguarda o usuário digitar algo no terminal e pressiona Enter
#O valor digitado será armazenado na variável 'argumento'
#Mostra o primeiro argumento passado na linha de comando quando o script foi chamado

echo "primeiro argumento"

read argumento

echo "$argumento"
echo "$1"


