#!/bin/bash

#Você criou um array
#Mostrou todos os elementos
#Acessou um valor específico
#Removeu esse valor (unset)
#Recolocou outro valor na mesma posição
#Mostrou o array atualizado

transport=('car' 'train' 'bike' 'bus')

echo "all arguments from array"
echo "${transport[@]}"

echo "single argument from array"
echo "${transport[1]}"

echo "removing argument from array"
unset transport[1]

echo "insert argument in array"
transport[1]='car_ride'

echo "${transport[@]}"