#!/bin/bash

#verifica se count é igual a 10
#se sim, mostra que são iguais, caso contrário, mostra que não são

#verifica se count é diferentede 10
#se sim, mostra que são diferentes, caso contrário, mostra que não são diferentes

count=10

if [ $count -eq 10 ]
then
echo "iguais"
else
echo "não iguais"
fi

if [ $count -ne 10 ]
then 
echo "diferentes"
else
echo "não diferentes"
fi


