#!/bin/bash

#recebe um valor como parâmetro
#verifica se esse valor é igual
#se forem, mostra que são iguais, caso contrário, mostra que não são

value="guessme"

guess=$1

if [ "$value" = "$guess" ]
then
echo " they are equal"
else
echo "they are not equal"
fi