#!/bin/bash

#verifica se o arquivo é gravável e se ele existe
#se verdadeiro, escreve 'hello world' no arquivo
#caso contrário, cria o arquivo e escreve 'hello world' no arquivo

filename=$1

if [ -f "$filename" ] && [ -w "$filename" ]
then
echo "hello world!" > $filename
else
touch "$filename"
echo "hello world!" > $filename
fi
